# This file is not installed; it is used only to make sure the strings
# used by Python's optparse module are translated.
_("no such option: %s")
_("ambiguous option: %s (%s?)")
_("Usage: %s\n")
_("Usage")
_("integer")
_("long integer")
_("floating-point")
_("complex")
_("option %s: invalid %s value: %r")
_("option %s: invalid choice: %r (choose from %s)")
_("show this help message and exit")
_("show program's version number and exit")
_("%prog [options]")
_("%s option requires an argument")
_("%s option requires %d arguments")
_("%s option does not take a value")
_("%s option requires an argument")
_("%s option requires %d arguments")
_("Options")
